feat(sécurité): ajoute la gestion du refresh token qui permet de déco…
MTES-MCT/camino-api pull request #492
Opened 2020-07-28 13:06 UTC by vmaubert

…nnecter un utilisateur

2020-07-28 13:07 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [tech: les tokens jwt sont valides à vie, donc si un token fuite on a aucun moyen de le bannir sauf en changeant le secret qui bannit tous les tokens](https://trello.com/c/lKY5ydgm/913-tech-les-tokens-jwt-sont-valides-%C3%A0-vie-donc-si-un-token-fuite-on-a-aucun-moyen-de-le-bannir-sauf-en-changeant-le-secret-qui-bann)

2020-07-28 13:41 UTC, vmaubert commented
/!\ Pour tester de pas oublier de mettre la nouvelle variable JWT_REFRESH_SECRET dans votre .env

2020-09-07 07:45 UTC, francoisromain approved these changes

2020-09-07 08:00 UTC, risseraka requested changes

2020-09-07 08:00 UTC, risseraka commented on src/server/graphql.ts
> +const graphql = graphqlHTTP((request: IAuthRequestHttp, response) => ({
Ajouter le typage de `response`.

2020-09-17 07:09 UTC, closed without merging