fix(activites): corrige l'url de sondage de la démarche selon le type d'activité
MTES-MCT/camino-api pull request #496
Opened 2020-08-11 08:59 UTC by NeoBahamut

2020-08-11 09:00 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix: le sondage "je donne mon avis sur cette démarche" renvoit vers une page guynae, même quand je rempli un rapport w](https://trello.com/c/p8titL6A/957-fix-le-sondage-je-donne-mon-avis-sur-cette-d%C3%A9marche-renvoit-vers-une-page-guynae-m%C3%AAme-quand-je-rempli-un-rapport-w)

2020-08-24 08:30 UTC, vmaubert requested changes

2020-08-24 08:30 UTC, vmaubert commented on src/api/graphql/resolvers/_titre-activite.ts
> +    type && type.satisfactionUrl ? type.satisfactionUrl : ''
Tu peux utiliser le [Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) de Typescript pour avoir une condition plus lisible.

2020-08-25 06:02 UTC, vmaubert approved these changes

2020-08-25 08:09 UTC, francoisromain requested changes

2020-08-25 08:09 UTC, francoisromain commented on src/api/graphql/schemas/metas-activites.graphql
> +  satisfactionUrl: String
pourquoi l'exposer dans graphql ? on n'en a pas besoin sur le front.

2020-09-10 11:43 UTC, francoisromain approved these changes

2020-09-10 11:45 UTC, merged