[WIP] feat(stats): améliore la page statistiques
MTES-MCT/camino-api pull request #502
Opened 2020-08-24 12:15 UTC by NeoBahamut

2020-08-25 08:20 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(stat): améliore la page statistiques](https://trello.com/c/qRYGONEx/949-featstat-am%C3%A9liore-la-page-statistiques)

2020-08-31 09:24 UTC, vmaubert requested changes

2020-08-31 09:24 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +        .subtable.reduce((acc: any[], eventAction: { label: string }) => {
Tu utilises un `reduce` au lieu d’un `filter`. À part si tu mets le `map` suivant dedans.

2020-08-31 14:26 UTC, NeoBahamut commented on src/tools/api-matomo/index.ts
> +    //   |->   nb_events : le nombre d'action de l'évènement
C'est juste pour mémoire. Je ne peux pas typer tout ce que l'API Matomo renvoie.

2020-08-31 14:27 UTC, NeoBahamut commented on src/tools/api-matomo/index.ts
> +  const matomoVisitData = await fetch(pathVisit).then(res => res.json())
Les commentaires sont pour mémoire.

2020-09-01 13:53 UTC, merged