feat(data): répertorie les étapes en base dont le type n'est pas paramétré dans le tableau TDE
MTES-MCT/camino-api pull request #510
Opened 2020-08-28 08:02 UTC by NeoBahamut

2020-08-28 08:03 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(data): répertorie les étapes en base dont le type n'est pas paramétré dans le tableau TDE](https://trello.com/c/LcVn4mnF/986-featdata-r%C3%A9pertorie-les-%C3%A9tapes-en-base-dont-le-type-nest-pas-param%C3%A9tr%C3%A9-dans-le-tableau-tde)

2020-08-31 07:50 UTC, vmaubert requested changes

2020-08-31 07:50 UTC, vmaubert commented on dev/json/error-find-TDE.js
> +  .reduce((acc, etape) => {
On utilise l’opérateur `reduce` pour combiner souvent plusieurs opérateurs (par exemple `filter` et `map`). 
Ici le `reduce` sert uniquement à faire un `filter`, donc il n’apporte aucune valeur ajoutée. 
2 possiblités :

- Remplacer le `reduce` par un `filter`
- Remplacer le `map` par `reduce` directement (moins lisible mais plus efficace, car on parcourt qu’une seule fois la liste, mais ici la performance importe peu)

2020-08-31 12:05 UTC, vmaubert approved these changes

2020-08-31 12:05 UTC, merged