feat(stats): améliore la page statistiques
MTES-MCT/camino-api pull request #512
Opened 2020-09-03 08:12 UTC by NeoBahamut

2020-09-03 08:13 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(stat): améliore la page statistiques](https://trello.com/c/qRYGONEx/949-featstat-am%C3%A9liore-la-page-statistiques)

2020-09-03 10:07 UTC, vmaubert requested changes

2020-09-03 10:07 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +    await Promise.all(
À réfactorer c’est quasiment le même code que plus bas

2020-09-03 10:07 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +      return { month: month, value: nbErreur }
Je ne vois pas l’utilité de « month ». De plus je pense qu’on peut simplifier tout ça avec un seul reduce.

2020-09-03 10:07 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +        }[] = await (await fetch(pathErreur)).json()
Si on commence à utiliser le même type à plusieurs endroits, ne pas hésiter à créer un vrai type nommé.

2020-09-03 13:09 UTC, NeoBahamut commented on src/tools/api-matomo/index.ts
> +        }[] = await (await fetch(pathErreur)).json()
c'est pas tout à fait le même, alors j'ai adapter dans le refacto, du coup il n'y en a qu'1

2020-09-03 13:10 UTC, NeoBahamut commented on src/tools/api-matomo/index.ts
> +      return { month: month, value: nbErreur }
maintenant que c'est refactoré, le "month" est nécessaire...

2020-09-03 13:23 UTC, vmaubert requested changes

2020-09-03 13:23 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +  target: string,
C’est beaucoup mieux, mais je pense qu’on peut enlever la target pour simplifier et que ça soit plus lisible.
À la place, on peut passer le `path` qui a été préalablement construit par une méthode qui prend en param, `eventType`, `period` et un objet qui contient les params supplémentaires (ex: `flat`).
De plus, on peut faire le traitement de `data.value` via un callback pour éviter la condition plus bas.

2020-09-08 08:36 UTC, vmaubert requested changes

2020-09-08 08:36 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +  ).reduce((acc: number, nbErreur) => (acc += nbErreur.value), 150)
Pourquoi on initialise à 150 ?

2020-09-08 08:36 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +const getPath = (eventType: string, period: string, flat: string) =>
À la place de `flat` je pense qu’on peut mettre un objet optionnel `params` de type `{ [param: string]: string | number }`.
Comme ça on pourrait passer `flat` mais aussi d’autres params sans se poser de question, par exemple`{ flat: 1, foo: 'foo' }`

2020-09-08 14:16 UTC, NeoBahamut commented on src/tools/api-matomo/index.ts
> +  ).reduce((acc: number, nbErreur) => (acc += nbErreur.value), 150)
c'est une valeur historique, il y avait 150 corrections recensée grâce aux signalements d'erreur avant la mise en place de matomo.
On va retrouver la même chose avec 6 réutilisations connues des flux initiales

2020-09-08 14:54 UTC, vmaubert commented on src/tools/api-matomo/index.ts
> +  ).reduce((acc: number, nbErreur) => (acc += nbErreur.value), 150)
Ok ça roule.

2020-09-08 14:55 UTC, vmaubert approved these changes

2020-09-10 11:56 UTC, merged