fix(activité): repasse les activités `grp` et `gra` du statut `fer` fermé au statut `abs` absent
MTES-MCT/camino-api pull request #514
Opened 2020-09-07 10:55 UTC by risseraka

2020-09-07 11:51 UTC, vmaubert requested changes

2020-09-07 11:51 UTC, vmaubert commented on dev/json/titres-activites-update.js
> +    if (['gra', 'grb'].includes(a.type_id) && a.statut_id === 'fer') {
C’est `gra` et `grp` et non `grb` d’après la carte Trello.

2020-09-07 11:53 UTC, vmaubert approved these changes

2020-09-07 11:54 UTC, risseraka commented on dev/json/titres-activites-update.js
> +    if (['gra', 'grb'].includes(a.type_id) && a.statut_id === 'fer') {
Bien vu.

2020-09-08 16:55 UTC, francoisromain approved these changes

2020-09-08 16:56 UTC, merged