feat(flux): traquer les appels à l'API
MTES-MCT/camino-api pull request #515
Opened 2020-09-08 09:07 UTC by NeoBahamut

2020-09-08 09:07 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(flux): Traquer les appels à l'API qui ne sont pas des appels de l'UI (et donc les flux)](https://trello.com/c/m4ph7UE5/1005-featflux-traquer-les-appels-%C3%A0-lapi-qui-ne-sont-pas-des-appels-de-lui-et-donc-les-flux)

2020-09-08 14:03 UTC, vmaubert requested changes

2020-09-08 14:03 UTC, vmaubert commented on src/api/rest/index.ts
> +        JSON.stringify({
Je ne comprends pas pourquoi on fait un `stringify` puis un `parse`. On ne peut pas faire directement :
`Object.entries({
   format,
  ordre,
 ...
})
` ?

2020-09-08 14:03 UTC, vmaubert commented on src/api/rest/index.ts
> +    ).reduce((acc, param) => {
Pour gagner en lisibilité, j’aurai fait un `map` puis un `join`.

2020-09-10 11:54 UTC, francoisromain requested changes

2020-09-10 11:54 UTC, francoisromain commented on src/api/rest/index.ts
> +    console.log(
à supprimer

2020-09-10 12:16 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(flux): Traquer les appels à l'API qui ne sont pas des appels de l'UI (et donc les flux)](https://trello.com/c/m4ph7UE5/1005-featflux-traquer-les-appels-%C3%A0-lapi-qui-ne-sont-pas-des-appels-de-lui-et-donc-les-flux)

2020-09-10 12:22 UTC, francoisromain approved these changes

2020-09-10 12:56 UTC, merged