feat(flux) : ajoute 'régions' 'departements' 'communes' dans les properties des geojson
MTES-MCT/camino-api pull request #533
Opened 2020-09-18 14:14 UTC by NeoBahamut

2020-09-18 14:15 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(flux) : ajoute 'régions' 'departements' 'communes' dans les properties des geojson](https://trello.com/c/TaLGkQPR/1033-featflux-ajoute-r%C3%A9gions-departements-communes-dans-les-properties-des-geojson)

2020-09-21 14:48 UTC, francoisromain requested changes

2020-09-21 14:48 UTC, francoisromain commented on src/api/rest/format/titres.ts
> +const titreCommunesDepartementsRegions = (titre: ITitre) =>
ajouter un verbe à la fin du nom de la fonction. par exemple: `titreTerritoiresFind`

2020-09-21 15:32 UTC, francoisromain approved these changes

2020-09-21 15:33 UTC, merged