feat(forets): ajoute les forêts sur les titres
MTES-MCT/camino-api pull request #536
Opened 2020-09-23 12:02 UTC by vmaubert

2020-09-23 13:09 UTC, francoisromain commented on src/api/rest/format/titres.ts
> +      forets: titre.forets?.map(f => f.nom).join(', '),
join avec `;`

2020-09-23 13:09 UTC, francoisromain commented on src/api/rest/format/titres.ts
> +        forets: titre.forets?.map(f => f.nom).join(', '),
join avec `;`

2020-09-23 13:09 UTC, francoisromain commented on src/api/rest/index.ts
> +        surfaceEtape: { forets: { id: {} } },
pourquoi est ce que ça remonte dans `surfaceEtape` ? est ce que `forets` ne devrait pas plutôt être au même niveau que `communes` ?

2020-09-23 13:09 UTC, francoisromain commented on src/database/queries/territoires.ts
> +    forets.map(f => ({ id: f.id, nom: f.nom })),
pourquoi y a-t-il besoin de `map` ici ?

2020-09-23 13:32 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(geo): affiche la liste des forêts](https://trello.com/c/Q6KkIdd2/630-featgeo-affiche-la-liste-des-for%C3%AAts)

2020-09-23 13:34 UTC, vmaubert commented on src/api/rest/format/titres.ts
> +        forets: titre.forets?.map(f => f.nom).join(', '),
@francoisromain Dans l’export GeoJson c’est `,` qui est utilisé partout comme séparateur

2020-09-23 13:37 UTC, vmaubert commented on src/database/queries/territoires.ts
> +    forets.map(f => ({ id: f.id, nom: f.nom })),
Car ça ajoute la `surface` en base de données. Pour les `communes`, on ne fait pas cette manip et on se retrouve avec une colonne est totalement vide.

2020-09-23 13:43 UTC, francoisromain commented on src/database/queries/territoires.ts
> +    forets.map(f => ({ id: f.id, nom: f.nom })),
je vois. donc en fait la colonne `surface` dans la table `communes` ne sert à rien. Il faudrait la supprimer de la migration et du modèle. Le map quand a lui devrait être fait dans l'appel de la fonction. qu'en penses tu ?

2020-09-23 13:47 UTC, francoisromain commented on src/api/rest/format/titres.ts
> +        forets: titre.forets?.map(f => f.nom).join(', '),
ok pour ça :  
- `;` dans l'export en tableau 
- `, ` dans le GeoJson

mais il y a l'air d'avoir des incohérence malgré tout (p.e.: `communes.join(';')` dans le geojson)

2020-09-23 14:00 UTC, vmaubert commented on src/database/queries/territoires.ts
> +    forets.map(f => ({ id: f.id, nom: f.nom })),
Je viens de faire une modification pour supprimer la colonne et mieux gérer le champ `surface`

2020-09-23 14:28 UTC, francoisromain requested changes
un dernier chipotage sur les noms

2020-09-23 14:28 UTC, francoisromain commented on src/business/daily.ts
> +    const communesList = await communesGet()
`communes` et `forets`

2020-09-23 14:28 UTC, francoisromain commented on src/business/daily.ts
> +    const { communes, forets } = await titresEtapesAreasUpdate(
`{ titresCommunes, titresForets }`

2020-09-24 07:16 UTC, francoisromain approved these changes

2020-09-24 07:18 UTC, merged