feat: ajoute l'édition d'une administration
MTES-MCT/camino-api pull request #572
Opened 2020-10-26 17:17 UTC by francoisromain

2020-10-26 17:18 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: ajout de la gestion des permissions sur les pages administrations](https://trello.com/c/eEd8TKNs/1075-feat-ajout-de-la-gestion-des-permissions-sur-les-pages-administrations)

2020-10-26 17:19 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: édite une administration](https://trello.com/c/2Krqwlmp/1107-feat-%C3%A9dite-une-administration)

2020-10-27 08:41 UTC, vmaubert requested changes

2020-10-27 08:41 UTC, vmaubert commented on src/api/graphql/resolvers/administrations.ts
> +    return administrationGet(
Nous sommes dans un `try / catch` donc il faut conserver le `await`

2020-10-27 08:43 UTC, francoisromain commented on src/api/graphql/resolvers/administrations.ts
> +    return administrationGet(
corrigé

2020-10-27 08:55 UTC, vmaubert commented
Dans la fiche d’une administration

- L’adresse n’est pas complète, il manque les champs `adresse`
- Il manque le `type`
- Il manque le `service`
- lI manque l’accent sur `departement`
- Il manque la majuscule et l’accent sur `region`

2020-10-27 08:57 UTC, vmaubert approved these changes

2020-10-27 08:57 UTC, merged