feat(entreprise): permet d’archiver une entreprise
MTES-MCT/camino-api pull request #583
Opened 2020-11-09 13:18 UTC by vmaubert

2020-11-09 13:19 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(entreprise): permet d’archiver une entreprise](https://trello.com/c/hfjItAP8/1121-featentreprise-permet-darchiver-une-entreprise)

2020-11-09 13:51 UTC, francoisromain requested changes
2 petites remarques

2020-11-09 13:51 UTC, francoisromain commented on src/database/queries/entreprises.ts
> +  if (archive === false || archive) {
plus explicite: `archive !== undefined && archive !== null`

2020-11-09 13:51 UTC, francoisromain commented on tests/queries/entreprises.graphql
> +query Entreprises($archive: Boolean) {
on peut laisser tous les champs (ça sert à documenter l'API)

2020-11-09 14:15 UTC, vmaubert commented on tests/queries/entreprises.graphql
> +query Entreprises($archive: Boolean) {
C’est juste pour les tests ici, je ne pense pas qu’on utilise ce fichier pour la documentation, si ? 

2020-11-09 14:16 UTC, francoisromain commented on tests/queries/entreprises.graphql
> +query Entreprises($archive: Boolean) {
le dossier entier est en lien dans la doc: https://docs.camino.beta.gouv.fr/pages/Utilisation/02-graphql.html

2020-11-10 17:09 UTC, francoisromain approved these changes

2020-11-10 17:09 UTC, merged