feat(titres): permet de récupérer le centre géographique de chaque titre
MTES-MCT/camino-api pull request #589
Opened 2020-11-13 10:35 UTC by vmaubert

2020-11-13 10:37 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(titres): permet de récupérer le centre géographique de chaque titre](https://trello.com/c/0wzg3e8n/1128-feattitres-permet-de-r%C3%A9cup%C3%A9rer-le-centre-g%C3%A9ographique-de-chaque-titre)

2020-11-16 08:29 UTC, francoisromain requested changes
deux propositions

2020-11-16 08:29 UTC, francoisromain commented on src/api/graphql/schemas/titres.graphql
> +  geojsonCentre: Coordonnees
par cohérence on pourrait plutôt exposer un geojson d'un seul point: 

```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```

2020-11-16 08:29 UTC, francoisromain commented on src/api/_format/titres.ts
> +    if (fields.geojsonCentre) {
la fonction de calcul du centre peut se trouver dans `/tools/geojson.ts` et retourner un geojson pour un seul point (voir commentaire ci-dessous)

2020-11-16 11:10 UTC, francoisromain requested changes

2020-11-16 11:10 UTC, francoisromain commented on src/api/graphql/schemas/titres.graphql
> +  geojsonCentre: FeaturePoint
`FeaturePoint` contient `properties: FeaturePointProperties` qui contient des propriétés qui n'existent pas sur le centre. 

Il me semble plus pertient d'ajouter un type : 

```
type GeojsonCentre {
  type: FeatureType!
  properties: EtapeId!
  geometry: GeometryPoints!
}
```

2020-11-16 14:00 UTC, francoisromain approved these changes

2020-11-16 14:19 UTC, merged