feat(statistiques) : ajoute l'onglet Granulats Marins
MTES-MCT/camino-api pull request #608
Opened 2020-12-10 09:39 UTC by NeoBahamut

2020-12-10 09:40 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (statistique): ajoute onglet Granulats Marins](https://trello.com/c/dEei055r/1154-feat-statistique-ajoute-onglet-granulats-marins)

2020-12-10 09:51 UTC, vmaubert commented on src/api/graphql/resolvers/statistiques.ts
> +// ================== Granulats Marins ========================
Le fichier devient beaucoup trop gros. Je propose d’extraire 2 nouveaux fichiers pour les méthodes `build`, 1 pour les stats Guyane et 1 pour les granulats marins.

2020-12-10 09:59 UTC, NeoBahamut commented on src/api/graphql/resolvers/statistiques.ts
> +// ================== Granulats Marins ========================
ok

2020-12-10 10:39 UTC, francoisromain requested changes

2020-12-10 10:39 UTC, francoisromain commented on src/api/graphql/resolvers/statistiquesGranulatsMarins.ts
> +import * as camelcase from 'camelcase'
le nom du fichier sans camel

2020-12-10 10:39 UTC, francoisromain commented on src/api/graphql/resolvers.ts
> +import { statistiquesGuyane } from './resolvers/statistiquesGuyane'
PAS DE CAMEL DANS LE NOM DES FICHIERS !

2020-12-10 10:45 UTC, NeoBahamut commented on src/api/graphql/resolvers/statistiquesGranulatsMarins.ts
> +import * as camelcase from 'camelcase'
ah oui, c'est vrai...

2020-12-10 10:45 UTC, NeoBahamut commented on src/api/graphql/resolvers.ts
> +import { statistiquesGuyane } from './resolvers/statistiquesGuyane'
oups, désolé

2020-12-14 18:10 UTC, francoisromain commented
pourquoi la PR s'appelle "onglet". C'est un terme d'interface, or on est ici sur l'API.

2020-12-16 08:46 UTC, francoisromain approved these changes

2020-12-16 08:46 UTC, merged