feat(demarches): conditionne l'affichage du bouton de création de démarches
MTES-MCT/camino-api pull request #610
Opened 2020-12-15 09:36 UTC by NeoBahamut

2020-12-15 09:37 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: conditionne l'affichage du bouton de création de démarches](https://trello.com/c/eZ6w3y1j/1117-feat-conditionne-laffichage-du-bouton-de-cr%C3%A9ation-de-d%C3%A9marches)

2020-12-15 09:41 UTC, francoisromain approved these changes

2020-12-15 09:43 UTC, francoisromain reviewed
est ce qu'un utilisateur avec compte éditeur peut ajouter une démarche ?

2020-12-15 09:49 UTC, francoisromain requested changes
après reflexion, je pense que cette proriété `demarchesModification` ne devrait pas être ajouté depuis `titresTypesPermissionsQueryBuild`, mais depuis `titrePermissionQueryBuild`

2020-12-15 10:22 UTC, vmaubert requested changes

2020-12-15 10:22 UTC, vmaubert commented on src/database/queries/permissions/titres.ts
>      permissionCheck(user?.permissionId, ['admin']) &&
Je ne sais pas où est cette information, mais seulement les `super` et les `admins` peuvent ajouter des démarches ?

2020-12-15 10:22 UTC, vmaubert commented on src/database/queries/permissions/titres.ts
> +    q.select(demarchesCreationQuery.as('demarchesCreation'))
Je pense que `demarchesCreation` dépend aussi de la valeur de `modification`. Si on a pas le droit de modifier un titre, alors on ne peut pas créer de démarche.

2020-12-16 08:41 UTC, francoisromain approved these changes

2020-12-16 08:42 UTC, merged