feat(activités): peux rendre les documents optionnels
MTES-MCT/camino-api pull request #625
Opened 2021-01-22 14:52 UTC by francoisromain

2021-01-22 14:53 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(rapport): rend le depôt du pdf facultatif pour les rapports annuels de production pour les AEX](https://trello.com/c/AIqKyyHF/1178-fixrapport-rend-le-dep%C3%B4t-du-pdf-facultatif-pour-les-rapports-annuels-de-production-pour-les-aex)

2021-01-27 15:39 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [Impossibilité d'ajouter un doc PDF dans l'étape "demande" d'une prolongation de PEC](https://trello.com/c/ecyWd9Ax/1200-impossibilit%C3%A9-dajouter-un-doc-pdf-dans-l%C3%A9tape-demande-dune-prolongation-de-pec)

2021-01-27 18:24 UTC, vmaubert requested changes
J’ai juste fait quelques retours, je testerai demain. 
À première vue c’est top 👏 , mais avec quelques tests ça serait 🚀

2021-01-27 18:24 UTC, vmaubert commented on dev/database/titres-activites-types-migrate.ts
> +    {},
Pour éviter les bugs et augmenter les perfs, mieux vaut préciser ce qu’on souhaite. Ici c’est juste `fields: { id: {}}`

2021-01-27 18:24 UTC, vmaubert commented on dev/database/titres-activites-types-migrate.ts
> +    delete ta.type
Inutile de le supprimer si pas chargé

2021-01-27 18:24 UTC, vmaubert commented on src/database/queries/titres-activites.ts
> +  { fields }: { fields?: IFields }
Pour des pbs de perfs sur le daily, on a commencé à enlever le « fetch » et donc `fields` sur les méthodes de suppression. Si on supprime un objet, c’est qu’on l’a déjà.

2021-01-27 18:34 UTC, francoisromain commented on dev/database/titres-activites-types-migrate.ts
> +    {},
je ne pense pas 
car on a besoin de copier aussi toutes les relations du type d'activité.

2021-01-27 18:34 UTC, francoisromain commented on dev/database/titres-activites-types-migrate.ts
> +    {},
pas de pb de perf ici. Le script tournera une fois lors du déploiement. Il met 2sec.

2021-01-27 18:34 UTC, francoisromain commented on dev/database/titres-activites-types-migrate.ts
> +    delete ta.type
oui

2021-01-27 18:35 UTC, francoisromain commented on src/database/queries/titres-activites.ts
> +  { fields }: { fields?: IFields }
ok

2021-01-28 09:09 UTC, vmaubert approved these changes

2021-01-28 09:09 UTC, merged