feat: ajoute une propriété suppression sur les activités invalides
MTES-MCT/camino-api pull request #651
Opened 2021-02-10 18:10 UTC by francoisromain

2021-02-10 18:14 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(activités): rend les rapports supprimables](https://trello.com/c/X4WtMxju/1163-featactivit%C3%A9s-rend-les-rapports-supprimables)

2021-02-11 13:02 UTC, vmaubert requested changes

2021-02-11 13:02 UTC, vmaubert commented on src/database/queries/permissions/titres-activites.ts
> +    q.select(raw('false').as('suppression'))
Donc on se retrouve avec 2 colonnes suppression dans le select ? Ça fait pas un potentiel conflit ?

2021-02-11 13:08 UTC, francoisromain commented on src/business/processes/titres-activites-props-update.ts
> +
non ça ne fait pas la même chose: `titreActiviteValideCheck` va exclure les activités qui ont été créées avant la date de début du type d'activité.

2021-02-11 13:08 UTC, francoisromain commented on src/business/validations/titre-etape-numbers-validate.ts
> +// TODO: ce fichier n'est utilisé nulle part. à supprimer ?
ok

2021-02-11 13:09 UTC, francoisromain commented on src/database/queries/permissions/titres-activites.ts
> +    q.select(raw('false').as('suppression'))
ça n'override pas ? J'ai regardé sur le front la prop ne s'affiche que si l'utilisateur est `super`

2021-02-11 13:12 UTC, francoisromain commented on src/business/processes/titres-activites-props-update.ts
> +
ici on veut juste vérifier que le titre était valide au moment ou l'activité a été créée

2021-02-11 13:12 UTC, francoisromain commented on dev/database/titres-activites-delete.ts
> +          propId => ta.contenu!.renseignements![propId]
ok

2021-02-11 15:32 UTC, vmaubert approved these changes

2021-02-11 15:32 UTC, merged