fix(étape):  corrige le libellé "récépissé" dans les déclarations loi sur l'eau
MTES-MCT/camino-api pull request #685
Opened 2021-03-05 13:55 UTC by NeoBahamut

2021-03-05 13:56 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(étape) : faute d'orthographe dans l'étape récépissé déclaration loi sur l'eau](https://trello.com/c/oB2utMME/1401-fix%C3%A9tape-faute-dorthographe-dans-l%C3%A9tape-r%C3%A9c%C3%A9piss%C3%A9-d%C3%A9claration-loi-sur-leau)

2021-03-08 10:14 UTC, vmaubert approved these changes

2021-03-08 11:00 UTC, francoisromain requested changes
bug: si `contenu` n'est pas mis à jour, alors `heritageContenu` n'est pas mis à jour.

2021-03-08 11:06 UTC, vmaubert approved these changes

2021-03-08 11:06 UTC, francoisromain approved these changes

2021-03-08 11:10 UTC, merged