[WIP] tooling: exporte les tables identifiées dans /sources au format json
MTES-MCT/camino-api pull request #689
Opened 2021-03-10 10:43 UTC by NeoBahamut

2021-03-10 12:25 UTC, francoisromain requested changes
on a besoin de 
- supprimer le dossier `sources` si il existe 
- dropper toutes les tables de la base de données
- ensuite `npm run db:init` doit fonctionner à partir du nouveau dossier `sources`

2021-03-15 06:41 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [se passer des spreadsheets](https://trello.com/c/1pHuOOCd/1021-se-passer-des-spreadsheets)

2021-03-15 15:42 UTC, vmaubert requested changes

2021-03-15 15:42 UTC, vmaubert commented on src/tools/exportDataBaseToJson.ts
> +const camelToSnakeCase = (field: string) =>
Je crois qu’on l’a déjà ça, @francoisromain ?

2021-03-15 15:42 UTC, vmaubert commented on src/tools/exportDataBaseToJson.ts
> +    const jsonFileName = `${tableName.replace(/_/g, '-')}.json`
Je crois qu’on a déjà un utilitaire pour ça, @francoisromain ?

2021-03-15 15:42 UTC, vmaubert commented on src/tools/exportDataBaseToJson.ts
> +const main = () => databaseToJsonExport()
T’as pas un pb avec le async/await ?

`
databaseToJsonExport()
  .then(() => {
    process.exit()
  })
  .catch(() => {
    process.exit(1)
  })
`

2021-03-15 17:15 UTC, francoisromain requested changes
ce serait bien de faire le singleton knex avant de merger cette PR. @vmaubert 

il est utilisé ici : https://github.com/MTES-MCT/camino-api/pull/689/files#diff-1db3872c94f6300144a0f207a1739031e79bfea3125bd0b78dd44a23e0ea7f3dR26

2021-03-16 08:19 UTC, francoisromain approved these changes

2021-03-16 08:28 UTC, merged