refactor: supprime la gestion des permissions dans les resolvers
MTES-MCT/camino-api pull request #695
Opened 2021-03-16 12:42 UTC by francoisromain

2021-03-16 13:28 UTC, vmaubert requested changes

2021-03-16 13:28 UTC, vmaubert commented on src/api/graphql/resolvers/titres-demarches.ts
>      const user = context.user && (await userGet(context.user.id))
Je crois qu’on peut enlever le chargement du user dans quasiment tous les resolvers 🎉

2021-03-16 13:28 UTC, vmaubert commented on src/api/graphql/resolvers/titres-travaux-etapes.ts
> +    const titreTravaux = await titreTravauxGet(etape.titreTravauxId, {})
Ajouter l’id du user en param

2021-03-16 13:28 UTC, vmaubert commented on src/api/graphql/resolvers/titres-travaux.ts
>      const travauxOld = await titreTravauxGet(id, {
C’est pas déjà fait juste au dessus ?

2021-03-16 18:20 UTC, francoisromain commented
il y a encore deux suites de tests qui plantent 
- titres.test.ts
- titres-demarches.test.ts

2021-03-17 14:51 UTC, merged

2021-03-18 12:01 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(administration): restreint les droits sur les travaux pour les administrations locales](https://trello.com/c/2Xs8QOcr/1096-featadministration-restreint-les-droits-sur-les-travaux-pour-les-administrations-locales)