[WIP] refacto: crée un dictionnaire pour la gestion des arbres
MTES-MCT/camino-api pull request #697
Opened 2021-03-16 15:29 UTC by NeoBahamut

2021-03-18 12:45 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [refacto: crée un dictionnaire pour les arbres](https://trello.com/c/g8x3A8ow/1417-refacto-cr%C3%A9e-un-dictionnaire-pour-les-arbres)

2021-03-19 09:05 UTC, vmaubert requested changes
Peux-tu vérifier que le daily ne change rien par rapport à master stp ?
Peux-tu aussi lancer le script `node ./dist/scripts/demarches-definitions-check.js` qui vérifie la cohérence des demandes en bdd.
Merci 👍

2021-03-23 07:40 UTC, NeoBahamut commented on src/business/rules-demarches/definitions.test.ts
> +      ).map(r => r.split('-')[0])
sans soucis

2021-03-23 07:41 UTC, NeoBahamut commented on src/business/rules-demarches/definitions.test.ts
>    test.each(demarchesDefinitions)(
Ok, en effet

2021-03-23 08:10 UTC, NeoBahamut commented
> 
> 
> Peux-tu vérifier que le daily ne change rien par rapport à master stp ?
> Peux-tu aussi lancer le script `node ./dist/scripts/demarches-definitions-check.js` qui vérifie la cohérence des demandes en bdd.
> Merci 👍

$ node ./dist/scripts/demarches-definitions-check.js

- - -
vérification des démarches

erreurs : 0

2021-03-23 08:32 UTC, vmaubert approved these changes

2021-03-23 08:38 UTC, francoisromain approved these changes

2021-03-24 08:02 UTC, merged