[WIP] doc(): met à jour la documentation et les scripts
MTES-MCT/camino-api pull request #710
Opened 2021-03-30 13:04 UTC by NeoBahamut

2021-03-30 15:16 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [mettre à jour la doc et vérifier les scripts](https://trello.com/c/3iR4ttTL/1441-mettre-%C3%A0-jour-la-doc-et-v%C3%A9rifier-les-scripts)

2021-03-30 18:14 UTC, francoisromain requested changes

2021-03-30 18:14 UTC, francoisromain commented on knex/knex-config.js
> +const { knexConfig } = require('./config')
renommer le fichier `config-cli`

2021-03-30 18:14 UTC, francoisromain commented on knex/user-add-cli.js
> +  console.log('user :>> ', user)
pas de console.log dans le projet

2021-03-31 12:16 UTC, vmaubert approved these changes

2021-04-06 11:19 UTC, francoisromain approved these changes

2021-04-06 11:20 UTC, merged