fix(flux): complète les propriétésdes  points des périmètres absents dans les flux
MTES-MCT/camino-api pull request #713
Opened 2021-04-02 14:04 UTC by NeoBahamut

2021-04-02 14:04 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(flux): les 'nom' et 'description' des points des périmètres sont absents des flux](https://trello.com/c/Czf4mZ88/1443-fixflux-les-nom-et-description-des-points-des-p%C3%A9rim%C3%A8tres-sont-absents-des-flux)

2021-04-06 17:24 UTC, francoisromain requested changes

2021-04-06 17:24 UTC, francoisromain commented on src/tools/geojson.ts
> +      references: p.references
pouquoi exposer les références des points ?

2021-04-07 06:12 UTC, NeoBahamut commented on src/tools/geojson.ts
> +      references: p.references
Les références sont vides dans les geojson actuellement, comme le nom et la description.

2021-04-07 14:10 UTC, francoisromain commented on src/tools/geojson.ts
> +      references: p.references
@NeoBahamut est ce qu'on en a besoin ?

2021-04-07 14:26 UTC, NeoBahamut commented on src/tools/geojson.ts
> +      references: p.references
@francoisromain , je ne sais plus pourquoi on a ajouté le champ 'references' dans les geojson mais vu qu'il n'était pas renseigné je ne comprend pas l'intérêt de garder un champ vide.
Tu préfère qu'on le retire ?

2021-04-07 15:23 UTC, francoisromain approved these changes

2021-04-07 15:23 UTC, merged