feat(statut des étapes) : rajouter deux statuts
MTES-MCT/camino-api pull request #720
Opened 2021-04-13 13:10 UTC by NeoBahamut

2021-04-13 13:16 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(statut des étapes) : rajouter deux statuts](https://trello.com/c/M0Yp2lhh/1455-featstatut-des-%C3%A9tapes-rajouter-deux-statuts)

2021-04-13 15:11 UTC, francoisromain requested changes

2021-04-13 15:11 UTC, francoisromain commented on src/dev/database/etapes-statuts-dae-add.ts
> +  daeStatuts.forEach(async ds => await EtapesStatuts.query().insert(ds))
on ne peut pas utiliser `forEach` avec `async` : https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop/37576787#37576787

2021-04-13 15:20 UTC, francoisromain approved these changes

2021-04-13 16:28 UTC, vmaubert requested changes
Faut aussi que je regarde pour les arbres d’instructions

2021-04-13 16:28 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +  const titresEtapesDaeFav = await TitresEtapes.query()
Pourquoi ne pas faire le patch ici ? 

2021-04-13 16:28 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +  await Promise.all(
À supp

2021-04-13 16:28 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +
Ajouter l’ajout/supp des EtapeTypeEtapeStatut

2021-04-14 14:19 UTC, vmaubert requested changes

2021-04-14 14:19 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +    .andWhere('statutId', 'fav')
« Pour les étapes déjà existantes dans Camino, remplacer le statut "favorable" par "exempté d'étude d'impact", et le statut "défavorable" en "soumis à étude d'impact". » 
Donc c’est tout l’inverse

2021-04-14 14:19 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +    .where('etapeStatutId', 'fav')
Il manque la condition sur l’étapeType

2021-04-14 14:19 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +  for (const ds of daeStatuts) {
Je crois qu’on a pas besoin de boucle, on peut mettre le tableau en param directement

2021-04-15 07:11 UTC, vmaubert requested changes

2021-04-15 07:11 UTC, vmaubert commented on src/dev/database/etapes-statuts-dae-add.ts
> +      couleur: 'succes'
success

2021-04-15 07:34 UTC, vmaubert commented
@NeoBahamut tu peux mettre les json dans `sources` à jour après le passage du script stp ? 

2021-04-15 15:48 UTC, merged