feat(upload): renforce les capacités de téléversement
MTES-MCT/camino-api pull request #799
Opened 2021-09-20 16:15 UTC by dheavy

- téléversement à pauses et reprises
- barre de progression dans l'UI

2021-09-21 06:23 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +      document.id = `${document.date}-${document.typeId}-${hash}`
Pour les autres entités, j'ai directement mis ça dans le modèle

2021-09-21 06:23 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +      document.id = `${document.date}-${document.typeId}-${hash}`
Pour les autres entités, j'ai directement mis ça dans le modèle

2021-09-21 06:23 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +    if (document.fichierHasNew) {
En fait je crois que j'ai pas compris ton explication hier 😅

2021-09-21 06:23 UTC, vmaubert commented on src/api/graphql/schemas/documents.graphql
> +  fichierHasNew: Boolean
Variable exposée au public, donc en français

2021-09-21 06:23 UTC, vmaubert commented on src/server/upload.ts
> +export default upload
On essaye de migrer petit à petit vers des export nommé, faut qu'on en reparle tous les 2

2021-09-21 06:24 UTC, vmaubert reviewed
On voit ça ensemble tout à l'heure

2021-09-22 09:03 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +    if (document.fichierNouveau) {
pourquoi on ne fait plus `document.fichier = true` ?

2021-09-22 09:03 UTC, vmaubert commented on src/types.ts
> +type TUSEventUploadComplete = {
Je pense qu’on peut le mettre directement dans le seul fichier qui utilise ce type.

2021-09-22 12:03 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(upload): mettre un loader pendant l’upload d’un fichier.](https://trello.com/c/zURCD2ed/1668-featupload-mettre-un-loader-pendant-lupload-dun-fichier)

2021-09-22 13:41 UTC, dheavy commented on src/api/graphql/resolvers/documents.ts
> +    if (document.fichierNouveau) {
On le fait plus haut, ligne 163 (si document.fichierTemporaire, booléen qui remplace la vérif de document.fichierNouveau)

2021-09-23 14:19 UTC, vmaubert requested changes

2021-09-23 14:19 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +      delete document.fichierNouveau
C’est pas géré directement par la modèle ? 

2021-09-23 14:19 UTC, vmaubert commented on src/api/graphql/resolvers/documents.ts
> +    if (document.fichierNouveau) {
La ligne 163 a disparu, donc je repose ma question :-)

2021-09-23 14:19 UTC, vmaubert commented on src/server/upload.test.ts
> +    await dbManager.populateDb()
On peut le mettre dans le beforeAll, non ? Tu ne modifies pas la bdd dans ton test.

2021-09-23 15:09 UTC, dheavy commented on src/api/graphql/resolvers/documents.ts
> +    if (document.fichierNouveau) {
Effectivement, merci ! Ce bug décroche les liens entre fichier et correspondance en base pour les uploads via l'API (via l'UI ça marche car la valeur y est passé).

2021-09-28 12:10 UTC, vmaubert approved these changes

2021-09-28 12:10 UTC, merged