fix(activitesTypesEmail): corrige deux erreurs dans l'ajout et la requête d'email
MTES-MCT/camino-api pull request #829
Opened 2021-11-04 16:41 UTC by dheavy

- un ajout remplaçait une entrée existante
- la requête retournait une nombre erroné d'entrées

2021-11-04 16:44 UTC, dheavy commented
@vmaubert j'ai testé pour les envois d'emails. En fait j'ai un message d'erreur en local mais lié à la configuration du service d'envoi d'email, et comme je ne veux pas envoyer des emails intempestifs, je ne préfère pas avancer sur une config de prod en local... mais le payload à envoyer a l'air formé, j'arrive à sortir le paquet sur la console.
Question subsidiaire : en dehors des mails listés manuellement dans notre liste sur la page, il y a bien un envoi fait à des emails des administrations titulaires et autre liées à l'entreprise ?

2021-11-08 08:38 UTC, vmaubert requested changes

2021-11-08 08:38 UTC, vmaubert commented on src/api/graphql/resolvers/_titre-activite.ts
> +      ...new Set(
Je pense qu’on peut le faire directement dans le service d’envoi d’email.

2021-11-08 08:38 UTC, vmaubert commented on src/database/queries/administrations.ts
> +const administrationActiviteTypeEmailInsert = async (
Je crois qu’on nomme ces méthodes « create » partout, non ? 

2021-11-08 11:49 UTC, dheavy commented on src/api/graphql/resolvers/_titre-activite.ts
> +      ...new Set(
Devenu obsolète avec l'insertion qui ne peut pas être doublonné.

2021-11-08 13:11 UTC, vmaubert commented on src/api/graphql/resolvers/administrations.ts
> +    } catch (e) {
on peut pas vérifier si c’est vraiment ça l’erreur ? 

2021-11-08 14:04 UTC, vmaubert approved these changes

2021-11-08 14:33 UTC, merged