feat(travaux): implémente les arbres de statuts
MTES-MCT/camino-api pull request #834
Opened 2021-11-15 11:47 UTC by dheavy

2021-11-15 14:12 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +  test.each([
Pourquoi ne pas utiliser la syntaxe habituelle ? 
```
test.each`
  a    | b    | expected
  ${1} | ${1} | ${2}
  ${1} | ${2} | ${3}
  ${2} | ${1} | ${3}
`('returns $expected when $a is added $b', ({a, b, expected}) => {
  expect(a + b).toBe(expected);
});
```

2021-11-17 09:06 UTC, vmaubert requested changes

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    ${'dam'}       | ${'pxm'}    | ${Travaux.Recolement}                     | ${'fav'} | ${'fpm'}
idem je suis pas certain de ça, à voir avec Laure

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    demarcheTypeId | titreTypeId | etapeTypeId                               | statutId | resultId
Trier par demarcheTypeId puis par ordre chrono pour une meilleure lisibilité. 
Ou peut-être même découper en 3 tests, 1 test par demarcheTypeId.

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  'rpu' // publication de décision au recueil des actes administratifs
wpa

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    demarcheTypeId | titreTypeId | etapeTypeId                               | statutId | resultId
Utiliser `DemarchesStatuts` pour le paramètre `resultId`

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  const statutId = titresDemarcheCommunesStatutIdFind(titreEtapeRecent)
Il y aucune étape commune entre les démarches et les travaux, donc je ne pense pas que ça soit utile.

2021-11-17 09:06 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  const titreEtapesDecisivesDemande = titreDemarcheEtapes.filter(titreEtape =>
`titreEtapesDecisivesDemande` me paraît plus cohérent.

2021-11-17 14:02 UTC, vmaubert requested changes

2021-11-17 15:38 UTC, dheavy commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  const titreEtapesDecisivesDemande = titreDemarcheEtapes.filter(titreEtape =>
Que veux-tu dire ?

2021-11-17 15:44 UTC, dheavy commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    ${'aom'}       | ${'pxm'}    | ${Travaux.AvisPrescriptionsDemandeur}     | ${'fav'} | ${'acc'}
J'ai posé les questions à Laure — je finalise selon ses réponses quand elle revient demain (idem pour la définition des "fin de police des mines").

2021-11-18 08:39 UTC, vmaubert requested changes

2021-11-18 08:39 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    "pour une démarche de travaux de type $demarcheTypeId sur un titre, dont l'étape récente est $etapeTypeId au statut $statutId, le résultat est $resultId",
Il reste l’ancien paramètre `demarcheTypeId` dans le nom du test

2021-11-18 08:39 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    "pour une démarche de travaux de type $demarcheTypeId sur un titre, dont l'étape récente est $etapeTypeId au statut $statutId, le résultat est $resultId",
Il reste l’ancien paramètre `demarcheTypeId` dans le nom du test

2021-11-18 08:39 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  'rpu' // publication de décision au recueil des actes administratifs
Pourquoi t’as laissé `rpu` ?

2021-11-18 08:39 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  const titreEtapesDecisivesDemande = titreDemarcheEtapes.filter(titreEtape =>
désolé `titreEtapesDecisives`

2021-11-18 09:58 UTC, vmaubert requested changes

2021-11-18 09:58 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +const titreEtapesDecisivesDemandesTravauxTypes = [
`titreEtapesDecisivesTravauxTypes`

2021-11-18 10:27 UTC, dheavy commented on src/business/rules/titre-demarche-statut-id-find.test.ts
> +    ${'aom'}       | ${'pxm'}    | ${Travaux.AvisPrescriptionsDemandeur}     | ${'fav'} | ${'acc'}
Retour de Laure : 

_"Oui effectivement c'est normal car il s'agit d'une "déclaration" auprès de l'administration et non d'une demande d'autorisation. Si je fais le parallèle avec le droit à la construction. Si tu changes une fenetre tu dois faire une déclaration préalable de travaux, si tu ajoutes un pièce, il te faudra un permis de construire. C'est un peu la même idée. La déclaration est une procédure allégée car les impacts sont moindres."_

2021-11-18 14:10 UTC, merged

2021-11-29 10:06 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(statut) : afficher le statut des démarches travaux](https://trello.com/c/MkvaYuEF/35-featstatut-afficher-le-statut-des-d%C3%A9marches-travaux)