fix(travaux): corrige les passages de statuts de DADT
MTES-MCT/camino-api pull request #858
Opened 2021-12-15 13:25 UTC by dheavy

2021-12-15 16:54 UTC, vmaubert requested changes

2021-12-15 16:54 UTC, vmaubert commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  // - dans le cas d'une 'dam', l'Abandon est ignoré au profit du précédent statut
Je n’arrive pas à trouver cette règle.
D’après la carte Trello : «  si étape (peu importe la date) = wab, alors statut = désisté »

2021-12-15 17:09 UTC, dheavy commented on src/business/rules/titre-demarche-statut-id-find.ts
> +  // - dans le cas d'une 'dam', l'Abandon est ignoré au profit du précédent statut
Tu as raison, j'ai lu WPA au lieu de WAB

2021-12-16 13:42 UTC, vmaubert approved these changes

2021-12-16 13:42 UTC, merged